{
	"version": 1502688242,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/jogvermelho-sheet0.png",
		"images/jogador-sheet0.png",
		"images/jogador-sheet1.png",
		"images/jogazul-sheet0.png",
		"images/jogpreto-sheet0.png",
		"images/centro-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/tempo-sheet0.png",
		"images/verifica1-sheet0.png",
		"images/verifica1-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/carta-sheet0.png",
		"images/vermelho-sheet0.png",
		"images/preto-sheet0.png",
		"images/azul-sheet0.png",
		"images/animeazul-sheet0.png",
		"images/animeazul-sheet1.png",
		"images/sprite6-sheet0.png",
		"images/animevermel-sheet0.png",
		"images/animeverde-sheet0.png",
		"images/animepreto-sheet0.png",
		"images/sprite-sheet0.png",
		"images/ursinho-sheet0.png",
		"images/ursinho-sheet1.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/cartaplay-sheet0.png",
		"images/cartaplay-sheet1.png",
		"images/sensor-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"media/internet_connection.ogg",
		"media/menu selection click.ogg",
		"media/teclado #1 - efeito sonoro grátis e sem copyright.ogg",
		"media/collect_point_02.m4a",
		"media/collect_point_02.ogg",
		"media/lose sound 2 - 1_0.m4a",
		"media/lose sound 2 - 1_0.ogg",
		"media/jingle_lose_00.m4a",
		"media/jingle_lose_00.ogg",
		"media/jingle_win_00.m4a",
		"media/jingle_win_00.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}