{
	"version": 1503285951,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/jogador-sheet0.png",
		"images/jogpreto-sheet0.png",
		"images/carta-sheet0.png",
		"images/vermelho-sheet0.png",
		"images/preto-sheet0.png",
		"images/azul-sheet0.png",
		"images/animeazul-sheet0.png",
		"images/animeazul-sheet1.png",
		"images/verdecx-sheet0.png",
		"images/animevermel-sheet0.png",
		"images/animeverde-sheet0.png",
		"images/animeverde-sheet1.png",
		"images/animepreto-sheet0.png",
		"images/ursinho-sheet0.png",
		"images/ursinho-sheet1.png",
		"images/sprite8-sheet0.png",
		"images/cartaplay-sheet0.png",
		"images/cartaplay-sheet1.png",
		"images/trilha-sheet0.png",
		"images/seta-sheet0.png",
		"images/bgcenarioplay-sheet0.png",
		"images/logogame-sheet0.png",
		"images/bplay-sheet0.png",
		"images/animeblue-sheet0.png",
		"images/gameover-sheet0.png",
		"images/brestart-sheet0.png",
		"images/fwin-sheet0.png",
		"images/splashf-sheet0.png",
		"media/internet_connection.ogg",
		"media/menu selection click.ogg",
		"media/teclado #1 - efeito sonoro grátis e sem copyright.ogg",
		"media/collect_point_02.m4a",
		"media/collect_point_02.ogg",
		"media/lose sound 2 - 1_0.m4a",
		"media/lose sound 2 - 1_0.ogg",
		"media/jingle_lose_00.m4a",
		"media/jingle_lose_00.ogg",
		"media/jingle_win_00.m4a",
		"media/jingle_win_00.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}